parameters:
  hidden_size: 450
  latent_size: 28
  depth: 5
  encoding_method: "average"
  feature_dim: 32
  max_nb: 100
  max_decode_len: 100

training_parameters:
  num_epochs: 500
  beta: 0.000
  alpha: 1.0
  gamma: 1.0

input_data_paths:
  adj_matrices: "/Users/lukasmueller/github/lascroge/data/go2_test/adj.npy"
  features: "/Users/lukasmueller/github/lascroge/data/go2_test/feat.npy"

model_save_path: "/Users/lukasmueller/github/lascroge/models/go2_test/model.pth"