parameters:
  hidden_size: 300
  latent_size: 16
  depth: 3
  encoding_method: "average"
  feature_dim: 5
  max_nb: 100
  max_decode_len: 100

training_parameters:
  num_epochs: 500
  beta: 0.0
  alpha: 1.0
  gamma: 1.0

input_data_paths:
  adj_matrices: "../data/robot_graphs/adj_go1.npy"
  features: "../data/robot_graphs/feat_go1.npy"

model_save_path: "../models/model.pth"