parameters:
  hidden_size: 300
  latent_size: 16
  depth: 5
  encoding_method: "average"
  feature_dim: 8
  max_nb: 100
  max_decode_len: 100

training_parameters:
  num_epochs: 1000
  beta: 0.0
  alpha: 1.0
  gamma: 1.0

input_data_paths:
  adj_matrices: "/Users/lukasmueller/github/lascroge/data/robot_graphs/adj.npy"
  features: "/Users/lukasmueller/github/lascroge/data/robot_graphs/feat.npy"

model_save_path: "../models/model.pth"